### ISSUE TITLE
newrelic-infra.service fails to start because of invalid license

### ISSUE THREAD

**Issue by onnimonni** [DavSanchez/Nix-Relic#11]
Hey,

I'm not sure if I'm holding it wrong but I added this package and the overlay to my server and after the rebuild it fails with following message:
```
$ nix run nixpkgs#nixos-rebuild -- ...
...
restarting sysinit-reactivation.target
starting the following units: newrelic-infra.service
warning: the following units failed: newrelic-infra.service
● newrelic-infra.service - New Relic Infrastructure Agent
     Loaded: loaded (/etc/systemd/system/newrelic-infra.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-10-23 18:16:11 UTC; 363ms ago
 Invocation: 2bab0b5590714ed5a63a3389523fe16d
    Process: 50915 ExecStart=/nix/store/99rgsnwp54y54qn39jj9iayhfpbvpmdl-infrastructure-agent-1.53.0/bin/newrelic-infra-service -config /nix/store/wmc62bfav2bm2zqnjplr78xll7dcfz2w-newrelic-infra.yml (code=exited, status=1/FAILURE)
   Main PID: 50915 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
   Mem peak: 11.4M
        CPU: 27ms
Shared connection to X.Y.Z.W closed.
warning: error(s) occurred while switching to the new configuration
```

When I then ssh to the server and try to check what's wrong it complains about my license:
```
$ /nix/store/99rgsnwp54y54qn39jj9iayhfpbvpmdl-infrastructure-agent-1.53.0/bin/newrelic-infra-service -debug -config /nix/store/wmc62bfav2bm2zqnjplr78xll7dcfz2w-newrelic-infra.yml
INFO[0000] Creating service...
time="2024-10-23T18:36:52Z" level=error msg="can't load configuration file" component="New Relic Infrastructure Agent" error="invalid license. Check agent's config file or NRIA_LICENSE_KEY environment variable"
INFO[0000] child process exited                          exit_code=1

$ cat /nix/store/wmc62bfav2bm2zqnjplr78xll7dcfz2w-newrelic-infra.yml | grep license
# Option : license_key
license_key: "NRAK-XXXXXXXXXXXXXXXX"
```

I'm based in EU and I was initially thinking if it was because I was missing my account id and the `NEW_RELIC_REGION=EU` so I tried again after using them as env:
```
$ export NEW_RELIC_ACCOUNT_ID=4XXXXX3 NEW_RELIC_REGION=EU NRIA_LICENSE_KEY="NRAK-XXXXXXXXXXXXXXXXXXP"
$ /nix/store/99rgsnwp54y54qn39jj9iayhfpbvpmdl-infrastructure-agent-1.53.0/bin/newrelic-infra -validate
time="2024-10-23T18:31:14Z" level=info msg="config validation failed with error: invalid license. Check agent's config file or NRIA_LICENSE_KEY environment variable" component="New Relic Infrastructure Agent"
```

Should I setup the config and my license key in a different way? Is this happening because I have my data in EU and the agent somehow defaults to something else?

I definitely can see the license key in the web dashboard and I just redacted the values above to `XXXXXXXXX` so that someone else will not use my key:
<img width="996" alt="Screenshot 2024-10-23 at 21 41 05" src="https://github.com/user-attachments/assets/6be68d6a-284e-42d4-8431-f55c9b0e9d7e">

**Comment by DavSanchez** [comment]
Hi!

The keys starting with `NRAK-****` are **user keys**. In your screenshot, the user key is used by the guided install process to install the desired agent and also generate the key that is actually needed for it. New Relic has [different types of keys](https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/), and which one to use can depend on the monitoring being configured (browser, mobile, or general ingest).

In the case of the infrastructure agent, what you need to put in the configuration or in `NRIA_LICENSE_KEY` is an **ingest license key**. To generate one, when you are inside the New Relic platform:

- Click the user icon in the bottom left corner (should show the user name when you hover as in my screenshot)

<img width="650" alt="image" src="https://github.com/user-attachments/assets/329a73db-3163-43ee-a192-609a5ca4f8a9">

- In the many that opens, go to **API Keys**.
- Select **Create a key** blue button in the top right.
- In the menu that opens select `Ingest - License` as your **key type**, fill the other requested data and create it.

The generated key will then be available for copying and using in your config. I think passing `NEW_RELIC_REGION` should not be required.

Let me know if that helps!

**Comment by DavSanchez** [comment]
Btw, just [updated the agent to the latest version](https://github.com/DavSanchez/Nix-Relic/pull/12), let's see if I manage to get it upstreamed soon!

**Comment by onnimonni** [comment]
Thanks for the detailed answer, it was easy to follow and I can now see my server in New Relic Dashboard 🥳.

The different license keys were not definitely not obvious for me 😅.

Thanks for updating it as well 👍

**Comment by DavSanchez** [comment]
Most welcome! I think the NR documentation on keys could be more clear. I'll see if I can do something about it.
